export { default as FooterLogo } from "./FooterLogo.svg";
export { default as HeaderLogo } from "./HeaderLogo.svg";
export { default as FindIcon } from "./find_mentoring.svg";
export { default as FindIconActive } from "./find_mentoring_active.svg";
export { default as MypageIcon } from "./mypage_icon.svg";
export { default as MypageIconActive } from "./profile_active.svg";
export { default as AddIcon } from "./new_mentoring.svg";
export { default as AddIconActive } from "./new_mentoring_active.svg";
export { default as ProgressIcon } from "./progress.svg";
export { default as ProgressIconActive } from "./progress_active.svg";
export { default as ProfileIcon } from "./profile.svg";
export { default as PencilIcon } from "./pencil.svg";
export { default as HomePageImg } from "./HomePageImg.png";
export { default as MypageImg } from "./MypageImg.png";
export { default as WritePageImg } from "./WritePageImg.png";
export { default as PhoneIcon } from "./phone_icon.svg";
export { default as LogoutIcon } from "./logout_icon.svg";
export * from "./ImgAdd";
